### PR TITLE
tests(Makefile): Update eask's commands

### PR DESCRIPTION
**Pull request by jcs090218**
This fixes CI.

### CODE REVIEW

**Comment by kurnevsky** [comment]
Thanks. It seems it didn't fix the CI. Is there anything left to do? :)

**Comment by jcs090218** [comment]
The error is:

```
lsp-metals-treeview.el:338:1:Error: Wrong number of arguments: (1 . 1), 0
```

Due to #81. It's an issue from upstream, https://github.com/Alexander-Miller/treemacs/issues/982. Nothing I can do for the issue. (Not in this PR)

Hence, nothing left to do.

**Comment by kurnevsky** [comment]
Ah, ok, thanks. I got confused by a lot of `Can't find library` errors :)

**Comment by jcs090218** [comment]
> Ah, ok, thanks. I got confused by a lot of Can't find library errors :)

Ah, yes. It's discussed in https://github.com/emacs-eask/cli/issues/11. I guess it's a known issue from Eask. Sorry for the confusion!

**Comment by kurnevsky** [comment]
It doesn't make things worse, so I'll merge this. Thanks.

**Pull request merged**
