### PR TITLE
Support launch.json and debug attach

### LINKED ISSUE #41: Debug via attach is supported in metals but not working in lsp-metals.
**Describe the bug**
Scala in emacs can be debugged via -java-debug option.

Using codelens we can debug a Runnable scala file.

I have a sbt project, where I run sbt -java-debug 1234. From Intellij I can connect to this remote debugger easily. I am unable to attach to this debugger via emacs.

**To Reproduce**
run
`sbt new playframework/play-scala-seed.g8`

start remote debugger
`sbt -java-debug 1234` (might have to change the port`.

Next step (which is missing). - attach the remote debugger to emacs.

**Expected behavior**
I would like to use remote debugger via emacs. This entire process is supported by metals. I have successfully attached this in intellij.

### LINKED ISSUE #49: Starting a debug session with the ui
When I try start a debug session using the ui menu instead of the lens I get the following error:
`Error running timer: (wrong-type-argument stringp nil)`

I suspect that the problem is related with my template:

```
(dap-register-debug-template
  "Analyzer"
  (list :type "scala"
        :request "debug"
        :name "Analyzer"
        :projectName "Analyzer"
        :mainClass "analyzer.Main"
        :args "blah bl;ah"
        :vmArgs ""))
```

Is there anything wrong with the template? Where can I find a template that works? I can't find any.

### PR DESCRIPTION
**Pull request by yyoncho**
Fixes #41
Fixes #49

### CODE REVIEW

**Review by abhijeetsrivastava — APPROVED** [review]
Works in my local

**Comment by gagbo** [comment]
Is there any blocker on this ? The CI failed on a (hopefully) totally unrelated error when Cask was fetching deps

```
Some dependencies were not available: treemacs, ht, f, dap-mode, lsp-treemacs, lsp-mode, scala-mode, scala-mode
```

**Comment by yyoncho** [comment]
I will merge it as it is. If @kurnevsky has comments they will be addressed separately

**Comment by gagbo** [comment]
Oh, I forgot to add a comment, apparently @tomahna has been testing the PR and a `:type` key is missing in the `dap-debug-template` call somehow.

**Comment by yyoncho** [comment]
@gagbo yes, it is missing on line 564.

**Pull request merged**
