### PR TITLE
Move lsp-metals-treeview.

### PR DESCRIPTION
**Pull request by kurnevsky**
@dsyzling want to help fixing checkdoc? :)

### CODE REVIEW

**Comment by dsyzling** [comment]
Yes no problem, I can take a look.

**Comment by dsyzling** [comment]
I've pushed up a branch - treeview-docs to my fork - wasn't sure about using this one. Do I need to create a pull request from that branch - or is there an easier way?

**Comment by dsyzling** [comment]
Are you copying over icons/metals from lsp-treemacs as well?

**Comment by kurnevsky** [comment]
> I've pushed up a branch - treeview-docs to my fork - wasn't sure about using this one. Do I need to create a pull request from that branch - or is there an easier way?

You can push in this branch, I was going to merge it only after CI succeeds.

> Are you copying over icons/metals from lsp-treemacs as well?

Forgot about them, need to move as well.

**Comment by dsyzling** [comment]
I'm not sure I've done that correctly - I've fetched the /pull/2/head branch into my fork and then pushed up as the 'treeview' branch in my fork - I don't think that's correct though.

**Comment by kurnevsky** [comment]
Pushed it myself. Thanks for the help!

**Pull request merged**
